### PR TITLE
Compatibility for allowAnything for Subcommands on CommandRunner

### PR DESCRIPTION
**Pull request by leoafarias**
This pull request is meant to fix issue #123

### CODE REVIEW

**Comment by leoafarias** [comment]
Seems that all tests passed but seeing an error 
``` The command "curl --connect-timeout 15 --retry 5 https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-linux-x64-release.zip > ${TRAVIS_HOME}/dartsdk.zip" failed and exited with 56 during .```

**Comment by leoafarias** [comment]
Seeing past merge requests I see there is a request to review so I will cc below
/cc @srawlins @munificent

**Comment by devoncarew** [comment]
@leoafarias, as a drive by comment, I think that this will later fail in `command_runner.dart`, where it tries to read from the `'help'` option:

```
      if (argResults['help']) {
        command.printUsage();
        return null;
      }
```

**Comment by devoncarew** [comment]
Guarding that access with a `results.options.contains('help') may work.

**Comment by devoncarew** [comment]
Thanks for the PR! I think this should be covered by https://github.com/dart-lang/args/pull/132.

**Pull request closed without merging**
