### PR TITLE
Document allowTrailingOptions in code

### PR DESCRIPTION
**Pull request by kasperpeulen**

### CODE REVIEW

**Comment by sethladd** [comment]
cool, thanks!

cc @munificent

**Comment by zoechi** [comment]
This isn't an improvement IMHO. Now when `null` is passed this breaks.

**Comment by kasperpeulen** [comment]
@zoechi Why would you pass `null`? I just like to see the default value here:

image

**Comment by zoechi** [comment]
I didn't say I want to pass `null`. What I say is that when passing `null`, the previous behavior was like `false` was passed but now it will probably throw eventually. That's a breaking change for no reason. You can still add a default value but the lines you removed below break the function.

**Comment by kasperpeulen** [comment]
@zoechi I agree, I changed those lines back.

**Comment by nex3** [comment]
Thanks for the patch!

**Pull request merged**
