### PR TITLE
Remove extra blank lines between options

### LINKED ISSUE #48: Provide an option not to add a newline after multiline option help
Consider:

```
$ flutter drive --help
Runs Flutter Driver tests for the current project.

Usage: flutter drive [arguments]
-h, --help                     Print this usage information.
    --[no-]checked             Toggle Dart's checked mode.
                               (defaults to on)

    --[no-]trace-startup       Start tracing during startup.
    --route                    Which route to load when starting the app.
-t, --target                   Target app path / main entry-point file.
                               (defaults to "lib/main.dart")

    --[no-]keep-app-running    Will keep the Flutter application running when done testing. By default Flutter Driver stops the application after tests are finished.
    --[no-]use-existing-app    Will not start a new Flutter application but connect to an already running instance. This will also cause the driver to keep the application running after tests are done.
    --debug-port               Listen to the given port for a debug connection.
                               (defaults to "8181")

Run "flutter help" to see global options.
```

The newlines after `--checked` and `--target` make it look like the options are grouped into three groups, which they are not.

### PR DESCRIPTION
**Pull request by natebosch**
Fixes #48

The extra blank lines imply a grouping, however the grouping is
arbitrary based on which options happened to wrap, and may vary based on
the terminal width. Instead keep all options without extra newlines.

### CODE REVIEW

**Comment by natebosch** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/pull/52552 for testing this change against the flutter tools presubmit

**Comment by jonahwilliams** [comment]
Analyze check failure is expected due to dependency override

**Comment by jonahwilliams** [comment]
Confusingly with this change, we now have some unexpected test failures unrelated to parsing. (Are there other changes in the args package that haven't been released?)

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/hermetic/precache_test.dart#L79

https://cirrus-ci.com/task/6256601757646848

**Comment by natebosch** [comment]
There were some performance optimizations made by @davidmorgan and @jakemac53 - I didn't review them so I don't have a guess as to whether they could be involved in this.

From the failure it looks like the last argument you passed got ignored?

What version were you synced to before so that we can narrow down the changes?

**Comment by jonahwilliams** [comment]
We're on 1.5.2 right now. At any rate, everything else looks good!

**Comment by davidmorgan** [comment]
Certainly could be related, I'll take a look.

**Comment by davidmorgan** [comment]
Yep--the change didn't allow underscores. Sorry about that. Sent https://github.com/dart-lang/args/pull/141

**Comment by jonahwilliams** [comment]
Thanks for the fix @davidmorgan

**Pull request merged**
