### PR TITLE
prep for publishing 1.5.3

### PR DESCRIPTION
**Pull request by devoncarew**
- prep for publishing `1.5.3`

### CODE REVIEW

**Comment by kevmoo** [comment]
Call it `-beta`? Then we distinguish between a release we're working on vs something shipped.

**Comment by natebosch** [comment]
Why do we need to publish as non-stable?

See https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change which explains our use of the `-dev` suffix

**Comment by devoncarew** [comment]
> Why do we need to publish as non-stable?

I'm also happy to publish this as the next stable release; I expect there's little chance that the change will be breaking for existing uses of the API.

**Comment by natebosch** [comment]
Have we written any code in google3 or the SDK or flutter that uses this?

https://github.com/dart-lang/args/pull/132#issuecomment-590475671

**Comment by natebosch** [comment]
cc @jakemac53

**Comment by devoncarew** [comment]
> Have we written any code in google3 or the SDK or flutter that uses this?
> 
> [#132 (comment)](https://github.com/dart-lang/args/pull/132#issuecomment-590475671)
> 
> An unmerged PR with a git override would be great for this.

There are no plans to take advantage of this change in google3 or flutter.

Google3 does pass w/ this change.

The SDK CL is here: https://dart-review.googlesource.com/c/sdk/+/137653. It also passes the presubmit tests.

**Comment by devoncarew** [comment]
fyi, publishing this now

**Pull request merged**
